In [1]:
from q1_softmax import *
from q2_gradcheck import *
from q2_sigmoid import *

# Some more magic so that the notebook will reload external python modules;
# see http://stackoverflow.com/questions/1907993/autoreload-of-modules-in-ipython
%load_ext autoreload
%autoreload 2

In [8]:
A = np.array([[0,0,0],[1,1,1],[2,2,2],[3,3,3],[4,4,4]])
rows = [0,1,1,2]
A[rows, :] += np.array([[0,0,0],[1,1,1],[1,1,1],[0,0,0]])
print A

[[0 0 0]
 [2 2 2]
 [2 2 2]
 [3 3 3]
 [4 4 4]]


## q1_softmax.py

In [12]:
test_softmax_basic()
test_softmax()

Running basic tests...
[[ 0.26894142  0.73105858]]
[[ 0.26894142  0.73105858]
 [ 0.26894142  0.73105858]]
[[ 0.73105858  0.26894142]]
You should verify these results!

Running your tests...
[[  6.33789383e-02   4.68310531e-01   4.68310531e-01]
 [  5.05610746e-44   5.00000000e-01   5.00000000e-01]]


## q2_gradcheck.py

In [16]:
sanity_check()
your_sanity_checks()

Running sanity checks...
Gradient check passed!
Gradient check passed!
Gradient check passed!

Running your sanity checks...
Gradient check passed!
Gradient check passed!
Gradient check passed!



## q2_sigmoid.py

In [17]:
test_sigmoid_basic()
test_sigmoid()

Running basic tests...
[[ 0.73105858  0.88079708]
 [ 0.26894142  0.11920292]]
[[ 0.19661193  0.10499359]
 [ 0.19661193  0.10499359]]
You should verify these results!

Running your tests...
[ 0.5]
[ 0.25]
You should verify these results!



## q2_neural.py

In [25]:
from q2_neural import *

%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [41]:
sanity_check()

Running sanity check...
Gradient check passed!


In [37]:
print y

[[ 0.30060961  0.33222499  0.3671654 ]]
